### ISSUE TITLE
After changing to 'Display Letter Instead of Skull for Difficulty', difficulty letters are displayed wrong

### ISSUE THREAD

**Issue by Azkel** [martinek/wow-progress#2]
Probably related to changes from acb2df7 commit - now if you have Difficulty as a letter set as true, you see letter at the end of the boss name, instead of aligned to the right side of the widget.

I'll try to fix this in the afternoon, and then offer a pull request for this bug ;)

**Comment by martinek** [comment]
I just now noticed this on my test page. On my side, problem was with old css being cached so new styles did not apply. Try reloading page without cache and see if it fixes it.
